services:
  clojure:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/demo
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  mysql_data:
